import { Chess, START_FEN, squareName } from '@check/chess';
declare global { interface ImportMeta { readonly env: Record<string,string|undefined> } }
const API=(import.meta.env.VITE_CHECK_SERVER_URL as string|undefined)||'http://localhost:8000';
const chess=new Chess(); const history:string[]=[]; let busy=false;
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const glyphs:Record<string,string>={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
function board():string{const lines:string[]=[];for(let rank=0;rank<8;rank++){let line=`${8-rank}  `;for(let file=0;file<8;file++){const piece=chess.board[rank*8+file];line+=`${piece?glyphs[piece]:'·'}  `;}lines.push(line);}return `${lines.join('\n')}\n\n   a  b  c  d  e  f  g  h`;}
function render():void{$('output').textContent=[...history.slice(-6),'',board(),'',`FEN  ${chess.fen()}`,busy?'◌ Server is thinking…':chess.status()||`${chess.turn==='w'?'White':'Black'} to move`].join('\n');$('screen').scrollTop=$('screen').scrollHeight;($('command') as HTMLInputElement).disabled=busy;}
async function post(path:string,body:unknown):Promise<{move:string;fen:string;explanation:string}>{const response=await fetch(API+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error((await response.text()).slice(0,180));return response.json();}
function exactMove(input:string):string|undefined{const normalized=input.replace(/[!?+#]/g,'').replace(/0/g,'O');const legal=chess.moves();const found=legal.find(move=>`${squareName(move.from)}${squareName(move.to)}${move.promotion||''}`===normalized.toLowerCase()||chess.san(move,legal).replace(/[+#]/g,'')===normalized);return found?`${squareName(found.from)}${squareName(found.to)}${found.promotion||''}`:undefined;}
async function play(input:string):Promise<void>{const lower=input.toLowerCase();if(lower==='help'){history.push('COMMANDS  e2e4 · Nf3 · natural language · fen · undo · new · help');return;}if(lower==='fen'){history.push(chess.fen());return;}if(lower==='undo'){chess.undo();if(chess.turn==='b')chess.undo();history.push('↶ Took back the last turn.');return;}if(lower==='new'){chess.load(START_FEN);history.length=0;history.push('New game started. You are White.');return;}busy=true;render();try{const local=exactMove(input);const result=local?{move:local,explanation:'notation'}:await post('/api/resolve',{instruction:input,fen:chess.fen()});const san=chess.play(result.move);history.push(`❯ ${input}`,`  You played ${san}${result.explanation&&result.explanation!=='notation'?` — ${result.explanation}`:''}`);if(chess.status())return;const engine=await post('/api/engine',{fen:chess.fen(),elo:Number(($('elo') as HTMLInputElement).value),depth:12});history.push(`  Stockfish played ${chess.play(engine.move)}`);}catch(error){history.push(`! ${error instanceof Error?error.message:String(error)}`);}finally{busy=false;}}
$('command-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const input=$('command') as HTMLInputElement;const command=input.value.trim();if(!command)return;input.value='';await play(command);render();input.focus();});history.push('Connected to Check Cloud. You are White.','Enter SAN, UCI, or describe a move naturally.');render();
